import React, { useState, useEffect } from 'react';

const TripStatusPanel = ({ tripDetails, onEndTrip }) => {
  const [elapsedTime, setElapsedTime] = useState(0);

  // This effect sets up a timer to track the trip duration
  useEffect(() => {
    const timer = setInterval(() => {
      // Calculate elapsed seconds from the start time
      setElapsedTime(Math.floor((new Date() - tripDetails.startTime) / 1000));
    }, 1000);

    // Cleanup the interval when the component unmounts
    return () => clearInterval(timer);
  }, [tripDetails]); // Dependency array ensures the timer restarts if the trip changes

  // Function to format seconds into MM:SS format
  const formatTime = (totalSeconds) => {
    const minutes = String(Math.floor(totalSeconds / 60)).padStart(2, '0');
    const seconds = String(totalSeconds % 60).padStart(2, '0');
    return `${minutes}:${seconds}`;
  };
  
  // This function will copy the sharable trip link to the clipboard
  const handleShareTrip = () => {
    // In a real app, this link would be generated by your backend
    const shareableLink = `https://yoursite.com/track/${tripDetails.id}`;
    navigator.clipboard.writeText(shareableLink);
    alert(`Sharable link copied to clipboard:\n${shareableLink}`);
  };

  return (
    <div className="trip-status-panel">
      <h3>Trip in Progress...</h3>
      <div className="timer">
        <p>Elapsed Time</p>
        <span>{formatTime(elapsedTime)}</span>
      </div>
      <div className="trip-actions">
        <button className="share-trip-button" onClick={handleShareTrip}>Share Trip</button>
        <button className="end-trip-button" onClick={onEndTrip}>End Trip</button>
      </div>
    </div>
  );
};

export default TripStatusPanel;

